// let arr1=[78,90,65,45,39];
//  console.log(arr1.splice(1,3));
//  console.log(arr1);
//  console.log(arr1.slice(1,3));
//  console.log(arr1.slice());
//  console.log(arr1.slice(1));
//  console.log(arr1.splice());
//  console.log(arr1);
//  console.log(arr1.splice(1));
//  console.log(arr1);
let arr2=[699,97,309,893,32];
// console.log(arr2.splice(1,3,78,90,788));
// console.log(arr2);
// console.log(arr2.splice(1,0,3));
// console.log(arr2);
let movies=["yjhd", "titanic","oppenheimar","idiots","barbie"];
let songs=["kabira","hii","byee","hello","biee"];
let merged=movies.concat(songs,arr2);
console.log(movies.unshift("paa"));
console.log(movies);
console.log(movies.shift());
console.log(movies);
console.log(movies.push("black"));
console.log(movies);
console.log(movies.pop());
console.log(movies);
console.log(movies.toString());
console.log(arr2.toString());
